{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecomm.fullname" . }}-frontend
  labels:
    {{- include "ecomm.componentLabels" (dict "ctx" $ "component" "frontend") | nindent 4 }}
  {{- if or .Values.commonAnnotations (and (eq .Values.frontend.service.type "LoadBalancer") .Values.frontend.service.annotations) }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if eq .Values.frontend.service.type "LoadBalancer" }}
    {{- with .Values.frontend.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.frontend.service.type "NodePort") .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
  {{- if eq .Values.frontend.service.type "LoadBalancer" }}
  {{- with .Values.frontend.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "ecomm.selectorLabels" (dict "ctx" $ "component" "frontend") | nindent 4 }}
{{- end }}
---
{{- if .Values.catalog.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecomm.fullname" . }}-catalog
  labels:
    {{- include "ecomm.componentLabels" (dict "ctx" $ "component" "catalog") | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.catalog.service.annotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.catalog.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.catalog.service.type }}
  ports:
    - name: http
      port: {{ .Values.catalog.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "ecomm.selectorLabels" (dict "ctx" $ "component" "catalog") | nindent 4 }}
{{- end }}
---
{{- if .Values.inventory.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecomm.fullname" . }}-inventory
  labels:
    {{- include "ecomm.componentLabels" (dict "ctx" $ "component" "inventory") | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.inventory.service.annotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.inventory.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.inventory.service.type }}
  ports:
    - name: http
      port: {{ .Values.inventory.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "ecomm.selectorLabels" (dict "ctx" $ "component" "inventory") | nindent 4 }}
{{- end }}
