{{- range $component := list "frontend" "catalog" "inventory" }}
{{- $svc := index $.Values $component }}
{{- if and $svc.enabled $svc.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ecomm.serviceAccountName" (dict "ctx" $ "component" $component "svcValues" $svc) }}
  labels:
    {{- include "ecomm.componentLabels" (dict "ctx" $ "component" $component) | nindent 4 }}
  {{- if or $.Values.commonAnnotations $svc.serviceAccount.annotations }}
  annotations:
    {{- with $.Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with $svc.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
